name = input("Enter your Name : ")
branch = input("Enter your Branch : ")
gender = input("Enter your Gender : ")
college = input("Enter your College : ")
age = input("Enter your Age : ")

print("Name : ",name)
print("Branch : ",branch)
print("Gender : ",gender)
print("College : ",college)
print("Age : ",age)
